### ISSUE TITLE
VS Code Extension replacing headers

### ISSUE THREAD

**Issue by azuravian** [pnp/sp-formatter#10]
This could be a user error on my part, but it appears that the extension has no way of knowing if you are in the header, body, or footer section of a form.

I was editing my footer using VS-Code and linked it to edge to view changes in real time.  By default, when choosing "Configure Layout" in a SPO form, it goes to Header.  Because of the connection, it immediately replaces all of the json in the Header section with the content of my "footer.form-formatter.json" file.

**Comment by s-KaiNet** [comment]
Yeah, sp-formatter currently doesn't detect it automatically, so if you want to modify footer, you should select footer drop down first, then connect VSCode. Currently I don't have plans to implement this feature.
