### ISSUE TITLE
Doesn't work on some tenants

### ISSUE THREAD

**Issue by s-KaiNet** [pnp/sp-formatter#4]
Users reported that the extension doesn't work for them. Tested on two different First Release tenants it works, meaning that SPO receives some updates, which break SP Formatter.

Link #3 because that's a high chance that they are related.

**Comment by dantshin** [comment]
@s-KaiNet, just FYR, my tenant is not running First Release (AFAIK). As I commented on your blog comments section, I was able to get the extension running today through CTRL-F5. I tried a regular refresh (F5/Ctrl-R), but it seemed that the hard refresh was what enabled the extension to load.

**Comment by s-KaiNet** [comment]
@dantshin thank you for the additional info! Anyway, after the current issue is fixed, `sp formatter` will be more stable. Maybe it will resolve your problem as well.

**Comment by s-KaiNet** [comment]
@dantshin the latest version `0.0.7` is available in the Chrome store. You can check whether it's more stable for you. Just make sure that Chrome updated the extension - under More Tools -> Extensions click on Details for SP Formatter and check the version.

**Comment by s-KaiNet** [comment]
I'm closing this issue for now. In case of any further problems please reopen or create a new one.
