### ISSUE TITLE
Tile formatting

### ISSUE THREAD

**Issue by marima84** [pnp/sp-formatter#7]
Hi,
thank you for this extension, very helpful!
I'm facing an issue when editing JSON code in Tile view. When I enable the extension the JSON code is reset to default view.
I’ve tested this behavior on both Microsoft Edge (101.0.1210.53) and Google Chrome (102.0.5005.6) on different SharePoint website. Same with the VS extension.

Thank you for your support

Mark

**Comment by s-KaiNet** [comment]
Hi, 
yeah, I was able to reproduce it, will work on a fix.

**Comment by s-KaiNet** [comment]
The fix is published and is currently going to the extension stores. Usually, it takes a few days until it will be published after the verification process. Thank you for reporting the issue!

**Comment by s-KaiNet** [comment]
Actually, it's already available for Chrome, could you please verify that it now works as expected in Chrome? Just make sure the version of the extension is 0.1.2

**Comment by marima84** [comment]
it works like a charm on Google Chrome. Actually on Edge as well installing the chrome extension... 😉
Thank you

**Comment by roamindev** [comment]
Just started using the extension and I love it! (Great work!!) But, I'm running into this same problem with Tile view formats. Using v0.1.2 of the extension and seeing the same thing in both Edge and Chrome. If I enable the extension and make a change or save the format, the view reverts to the default Tile/Gallery view. The custom JSON does remain in the editor until a refresh is performed, but has no affect on the actual view.

After refreshing the page, the view is still the default Tile view and when I select "Format custom view", I only see the default "Card Designer"/"Edit card" option from SP Online.

Please let me know if there's any other info I can provide to help identify what might be going on. Thanks!!

**Comment by s-KaiNet** [comment]
Hi, 

yeah... seems something was changed again, will take a look when I have time.

**Comment by FPmediaFlorian** [comment]
Hi ,

have you had a chance to take a look at the issue? Running into the same problem with Version 0.1.2.
Thanks!

Florian

**Comment by Lou-i3** [comment]
Hi, 

I have the same issue with tiles formatting... 
Have you had time to look at it? 
I'm running version 0.1.2.

Thanks a lot! 
Louis

**Comment by s-KaiNet** [comment]
Hi, yeah, I took a look sometime ago, but haven't found the fix yet. Unfortunately, the trick, which worked previously, doesn't work right now.

**Comment by s-KaiNet** [comment]
After a few more attempts, I found a fix for the issue. It's already available for Chrome version `0.1.3` and will be soon available for Edge (it's under review, normally they publish in 24hrs).
