### ISSUE TITLE
VS Code extension ClientFormCustomFormatter

### ISSUE THREAD

**Issue by Tanddant** [pnp/sp-formatter#8]
Hi @s-KaiNet, thanks for the awesome work on this extension 🙌 - Couldn't do my job without it 😅

I'm working on a Script Sample to backup any custom formatting on a SharePoint site, and I want then to work with the awesome VS code extension, but I've come across that there appers to be no way to save a file in the "correct" format for a form customization, is there any chance we'll see an expansion 🤞

> If your JSON formatting file name has one of the below endings:
> *.column-formatter.json, *.column.formatter.json, *.column-format.json, *.column.format.json
> OR
> *.view-formatter.json, *.view.formatter.json, *.view-format.json, *.view.format.json
Then your .json file will be the subject for additional intellisense.

**Comment by s-KaiNet** [comment]
Hello, thank you and sorry for the late reply. I don't see any problems to add additional intellisense for form customization as well. Will take a look how it could be imlemented.

**Comment by Tanddant** [comment]
Hey @s-KaiNet,

No worries, thanks for taking a look 😊

I called my forms .form-formatter.json, but if you feel like different names work better let me know and I'll update my other sample 


https://github.com/pnp/script-samples/pull/591/

**Comment by s-KaiNet** [comment]
This is completed in `0.0.7` version, which is already available in the marketplace.
