### ISSUE TITLE
New List View

### ISSUE THREAD

**Issue by ctm474** [pnp/sp-formatter#9]
It doesn't seem to be working in the 'newer' list view - The one where the views selector has been removed from the ribbon and placed between the ribbon and the column names

**Comment by s-KaiNet** [comment]
Could you provide some screenshots how it looks like?

**Comment by ctm474** [comment]
Sometimes lists want to open in the Microsoft Lists app layout - when they
do, it doesn't work
[image: Screenshot 2024-02-27 at 1.54.55 PM.png]


Sometimes they don't
[image: Screenshot 2024-02-27 at 1.59.39 PM.png]

**Comment by s-KaiNet** [comment]
Sorry, seems the screenshots pasted via email are not visible. Could add them thought the GitHub site?

**Comment by s-KaiNet** [comment]
@ctm474 Could you please re-add your screenshots using the Github website? Because I cannot see them in the response sent from email.

**Comment by azuravian** [comment]
I'm having the same problem.  Here is an example of the list view.

Top Right:
![image](https://github.com/pnp/sp-formatter/assets/7379812/cc04d90f-580d-4600-9267-b1b9acf5711a)

Top Left:
![image](https://github.com/pnp/sp-formatter/assets/7379812/7709943d-1eb8-45d6-9ee1-cd7575a234ca)

**Comment by sperley** [comment]
Getting the same problem.  Now that we can't switch back from the new MS Lists UI (Tabbed Views), it's causing more of an issue 😟

**Comment by s-KaiNet** [comment]
Now I see... will take a look what I can do.

**Comment by s-KaiNet** [comment]
I was able to identify the problem. Basically now column formatting related things are inside iframes and of course it breaks everything in sp-formatter. Fortunately, seems I can workaround it without much of the problems. I'm planning to fix it by the end of this week.

**Comment by s-KaiNet** [comment]
0.1.5 version was published yesterday and now is available for Chrome and will be available in a few days for Edge as well. 
Please make sure you use 0.1.5 version (can be verified under extension details page in chrome) and check if it fixes the issue.

**Comment by Lou-i3** [comment]
I tried on the new list view and it seems to be working fine. Thanks a lot! 

However, I tried on the document library view and it doesn't work there.

**Comment by s-KaiNet** [comment]
OMG I checked everything - column, form, view formatting, tiles mode, vscode integration. But totally forgot about document libraries - the core of SharePoint :)
I can see document libraries still use "old" approach without iframes, hopefully the fix will be simple.

**Comment by s-KaiNet** [comment]
Version 0.1.6 with fixed document libraries available in Chrome and will be available in Edge in 5 business days.

**Comment by Lou-i3** [comment]
All good from my side. Thanks a lot!

**Comment by s-KaiNet** [comment]
Great! I will close the issue then. If anybody still has problems, please reopen or create a new one.
